#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/../vendor/autoload.php';

use Doctrine2Eloquent\Command\YamlConverterCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new YamlConverterCommand());
$application->run();